### ISSUE TITLE
Error while container started

### ISSUE THREAD

**Issue by Rohlik** [ColinHuang/docker-ubuntu-novnc-armhf#1]
I got this error:
`exec format error`

**Comment by ColinHuang** [comment]
@Rohlik Are you running this container on ARMHF machine?

**Comment by Rohlik** [comment]
I running this command on my Docker host `docker run -d -p 6080:6080 colinhuang/ubuntu-novnc-armhf`

**Comment by Rohlik** [comment]
No, I use RHEL7. My bad...

**Comment by ColinHuang** [comment]
@Rohlik You can try other images: https://hub.docker.com/r/dorowu/ubuntu-desktop-lxde-vnc/.
